version: "3.8"
services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

  phpmyadmin:
    image: phpmyadmin
    env_file: .env
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}

  server:
    build: ./server
    restart: always
    depends_on:
      - mysql
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}

  mqtt-server-transfer:
    build: ./mqtt-server-transfer
    depends_on:
      - mysql
    env_file: .env

  client:
    build: ./client
    ports:
      - 80:80
    env_file: .env

volumes:
  mysql-data:
